[workspace]
members = [
    "ch3",
    "ch5-1",
    "ch5-2",
    "ch5-3",
    "ch5-4",
    "ch5-4-3",
    "ch5-5-2",
    "ch6",
    "ch7-1",
    "ch8-1",
    "ch9-1",
    "ch9-2",
    "ch10-1",
    "ch11-1",
    "ch12-1",
]
