#!/bin/bash
set -o allexport -o errexit -o privileged -o pipefail -o nounset

frogcfg_set_key array "package.common.namespaces" "common" "common.sysinfo" "common.lang.version" "common.remote"
frogcfg_set_key string "package.common.namespaces.common.desc" "Runs a common bullfrog operation."
frogcfg_set_key array "package.common.namespaces.common.operations" "version"
frogcfg_set_key string "package.common.namespaces.common.operations.version.lang" "bash"
frogcfg_set_key string "package.common.namespaces.common.operations.version.desc" "Displays bullfrog version"
frogcfg_set_key array "package.common.namespaces.common.operations.version.outputs" "json"
frogcfg_set_key array "package.common.namespaces.common.operations.version.parameters"
frogcfg_set_key string "package.common.namespaces.common.sysinfo.desc" "Provides system information tools"
frogcfg_set_key array "package.common.namespaces.common.sysinfo.operations" "default"
frogcfg_set_key string "package.common.namespaces.common.sysinfo.operations.default.lang" "bash"
frogcfg_set_key string "package.common.namespaces.common.sysinfo.operations.default.desc" "Displays a general profile of the system"
frogcfg_set_key array "package.common.namespaces.common.sysinfo.operations.default.outputs" "json"
frogcfg_set_key array "package.common.namespaces.common.sysinfo.operations.default.parameters"
frogcfg_set_key string "package.common.namespaces.common.lang.version.desc" "Displays version information for supported programming languages."
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations" "default" "js" "python" "rust" "java"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.default.lang" "bash"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.default.desc" "Displays version information for all supported languages."
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.default.outputs" "json"
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.default.parameters"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.js.lang" "js"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.js.desc" "Displays the system NodeJS and V8 versions."
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.js.outputs" "json"
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.js.parameters"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.python.lang" "python"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.python.desc" "Displays the system Python version."
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.python.outputs" "json"
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.python.parameters"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.rust.lang" "rust"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.rust.desc" "Displays the system RustC version."
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.rust.outputs" "json"
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.rust.parameters"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.java.lang" "java"
frogcfg_set_key string "package.common.namespaces.common.lang.version.operations.java.desc" "Displays the system JRE and JDK versions."
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.java.outputs" "json"
frogcfg_set_key array "package.common.namespaces.common.lang.version.operations.java.parameters"
frogcfg_set_key string "package.common.namespaces.common.remote.desc" "Runs bullfrog commands remotely via SSH"
frogcfg_set_key array "package.common.namespaces.common.remote.operations" "default" "install"
frogcfg_set_key string "package.common.namespaces.common.remote.operations.default.lang" "bash"
frogcfg_set_key string "package.common.namespaces.common.remote.operations.default.desc" "Displays the current remote host"
frogcfg_set_key array "package.common.namespaces.common.remote.operations.default.outputs"
frogcfg_set_key array "package.common.namespaces.common.remote.operations.default.parameters"
frogcfg_set_key string "package.common.namespaces.common.remote.operations.install.lang" "bash"
frogcfg_set_key string "package.common.namespaces.common.remote.operations.install.desc" "Installs bullfrog on the remote machine"
frogcfg_set_key array "package.common.namespaces.common.remote.operations.install.outputs"
frogcfg_set_key array "package.common.namespaces.common.remote.operations.install.parameters"

FROG_PACKAGE_NAMESPACE="common"
